In [31]:
import pandas as pd

race = '2016_pres'
df = pd.read_csv(race + '.csv')

col = list(df.columns)
col = col[2:-1]

final_dict = {'State':[], 'Num Seats': []}

for c in col:
    final_dict.update({c: []})

for index, row in df.iterrows():
    nm = row['state']
    seats = row['num_seats']
    
    left = seats

    votes = {'Votes': {}, 'Value': {}, 'Seats': {}}
    quot = []
    
    for c in col:
        votes['Votes'].update({c: row[c]})
        votes['Value'].update({c: row[c]})
        votes['Seats'].update({c: 0})
        quot.append(row[c])
        
    #print('\n------' + nm + '------')
    while left > 0:
        party = max(votes['Value'], key=lambda key: votes['Value'][key])
        votes['Seats'][party] +=1
        
        #print(str(party) + ', ' + str(votes['Value']))
        left -= 1
        try:
            votes['Value'][party] = votes['Votes'][party]/(votes['Seats'][party]+1)
        except:
            print('Make sure votes are in number format')
        
    final_dict['State'].append(nm)
    final_dict['Num Seats'].append(seats)
    
    for c in col:
        final_dict[c].append(votes['Seats'][c])
        
    #print(nm + ': ' + str(votes['Seats']))
        
final_df = pd.DataFrame(final_dict)
final_df.to_csv(race + '_dhondt.csv', index=False) 
    
final_df

             State  Num Seats  dem  gop  lib  green  mcmullin
0          Alabama          7    2    5    0      0         0
1           Alaska          1    0    1    0      0         0
2          Arizona          9    4    5    0      0         0
3         Arkansas          4    1    3    0      0         0
4       California         53   34   17    1      1         0
5         Colorado          7    4    3    0      0         0
6      Connecticut          5    3    2    0      0         0
7         Delaware          1    1    0    0      0         0
8          Florida         27   13   14    0      0         0
9          Georgia         14    7    7    0      0         0
10          Hawaii          2    2    0    0      0         0
11           Idaho          2    0    2    0      0         0
12        Illinois         18   11    7    0      0         0
13         Indiana          9    3    6    0      0         0
14            Iowa          4    2    2    0      0         0
15          Kansas          4    1    3    0      0         0
16        Kentucky          6    2    4    0      0         0
17       Louisiana          6    2    4    0      0         0
18           Maine          2    1    1    0      0         0
19        Maryland          8    5    3    0      0         0
20   Massachusetts          9    6    3    0      0         0
21        Michigan         14    7    7    0      0         0
22       Minnesota          8    4    4    0      0         0
23     Mississippi          4    2    2    0      0         0
24        Missouri          8    3    5    0      0         0
25         Montana          1    0    1    0      0         0
26        Nebraska          3    1    2    0      0         0
27          Nevada          4    2    2    0      0         0
28   New Hampshire          2    1    1    0      0         0
29      New Jersey         12    7    5    0      0         0
30      New Mexico          3    2    1    0      0         0
31        New York         27   17   10    0      0         0
32  North Carolina         13    6    7    0      0         0
33    North Dakota          1    0    1    0      0         0
34            Ohio         16    7    9    0      0         0
35        Oklahoma          5    1    4    0      0         0
36          Oregon          5    3    2    0      0         0
37    Pennsylvania         18    9    9    0      0         0
38    Rhode Island          2    1    1    0      0         0
39  South Carolina          7    3    4    0      0         0
40    South Dakota          1    0    1    0      0         0
41       Tennessee          9    3    6    0      0         0
42           Texas         36   16   19    1      0         0
43            Utah          4    1    2    0      0         1
44         Vermont          1    1    0    0      0         0
45        Virginia         11    6    5    0      0         0
46      Washington         10    6    4    0      0         0
47   West Virginia          3    1    2    0      0         0
48       Wisconsin          8    4    4    0      0         0
49         Wyoming          1    0    1    0      0         0